#!/bin/bash

set -e

cd "${0%/*}" # This changes your current directory to the one where the file is placed

if [ -f ./build/main ]; then
	./build/main "$@"
else
	echo "Program not compiled, call make first"
fi
